jQuery.fn.exists=function(){return $(this).length;}
var $frame=$('#main-slider');var $wrap=$frame.parent();$frame.sly({horizontal:1,itemNav:'basic',smart:1,activateOn:'click',mouseDragging:1,touchDragging:1,releaseSwing:1,startAt:0,scrollBar:$('#slider-scrollbar'),scrollBy:1,speed:1000,elasticBounds:1,easing:'easeOutExpo',dragHandle:1,dynamicHandle:1,clickBar:1,cycleBy:'items',cycleInterval:4000,pauseOnHover:1,prev:$wrap.find('.prev-sl-sly'),next:$wrap.find('.next-sl-sly')});$(document).ready(function(){if($('.draw-summary .counter').exists()){$('.draw-summary .counter').counterUp({delay:10,time:1000});}
if($('#game-slider01').exists()){$('#game-slider01').slick({slidesToShow:3,slidesToScroll:1,prevArrow:$('#slider01-prev-arrow'),nextArrow:$('#slider01-next-arrow'),infinite:false});}
if($('#game-slider02').exists()){$('#game-slider02').slick({slidesToShow:5,slidesToScroll:1,prevArrow:$('#slider02-prev-arrow'),nextArrow:$('#slider02-next-arrow'),infinite:false});}
function slideAdd(thisSlider,action,cnt,a){setTimeout(function(){$.get('/ajax/slick_v2.php?a='+action+'&c='+cnt+(a?'&p='+a:''),function(data){if(data.error==0){thisSlider.slick('slickAdd',data.html);return true;}},'json');},100);return false;};if($('#tab01-slider').exists()){tab01_slider=$('#tab01-slider').slick({slidesToShow:11,slidesToScroll:11,prevArrow:$('#tab01-slider-prev-arrow'),nextArrow:$('#tab01-slider-next-arrow'),infinite:false,vertical:true,verticalSwiping:true});var i_tab01=0;$('#tab01-slider-next-arrow').click(function(e){e.preventDefault();i_tab01++;if(i_tab01==1){var cnt=$('#tab01-slider div.item').length;$.get('/ajax/slick_v2.php?a=popular_games_v3&c='+cnt,function(data){if(data.error==0){tab01_slider.slick('slickAdd',data.html);tab01_slider.slick('slickNext');}},'json');}});$('#tab01-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#tab01-slider div.item').length;slideAdd(tab01_slider,'popular_games_v3',cnt);});}
if($('#tab02-slider').exists()){tab02_slider=$('#tab02-slider').slick({slidesToShow:11,slidesToScroll:11,prevArrow:$('#tab02-slider-prev-arrow'),nextArrow:$('#tab02-slider-next-arrow'),infinite:false,vertical:true,verticalSwiping:true});var i_tab02=0;$('#tab02-slider-next-arrow').click(function(e){e.preventDefault();i_tab02++;if(i_tab02==1){var cnt=$('#tab02-slider div.item').length;$.get('/ajax/slick_v2.php?a=new_games_v3&c='+cnt,function(data){if(data.error==0){tab02_slider.slick('slickAdd',data.html);tab02_slider.slick('slickNext');}},'json');}});$('#tab02-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#tab02-slider div.item').length;slideAdd(tab02_slider,'new_games_v3',cnt);});}
if($('#tab03-slider').exists()){tab03_slider=$('#tab03-slider').slick({slidesToShow:11,slidesToScroll:11,prevArrow:$('#tab03-slider-prev-arrow'),nextArrow:$('#tab03-slider-next-arrow'),infinite:false,vertical:true,verticalSwiping:true});var i_tab03=0;$('#tab03-slider-next-arrow').click(function(e){e.preventDefault();i_tab03++;if(i_tab03==1){var cnt=$('#tab03-slider div.item').length;$.get('/ajax/slick_v2.php?a=preorders_games_v3&c='+cnt,function(data){if(data.error==0){tab03_slider.slick('slickAdd',data.html);tab03_slider.slick('slickNext');}},'json');}});$('#tab03-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#tab03-slider div.item').length;slideAdd(tab03_slider,'preorders_games_v3',cnt);});}
if($('#tab04-slider').exists()){tab04_slider=$('#tab04-slider').slick({slidesToShow:11,slidesToScroll:11,prevArrow:$('#tab04-slider-prev-arrow'),nextArrow:$('#tab04-slider-next-arrow'),infinite:false,vertical:true,verticalSwiping:true});var i_tab04=0;$('#tab04-slider-next-arrow').click(function(e){e.preventDefault();i_tab04++;if(i_tab04==1){var cnt=$('#tab04-slider div.item').length;$.get('/ajax/slick_v2.php?a=actions_games_v3&c='+cnt,function(data){if(data.error==0){tab04_slider.slick('slickAdd',data.html);tab04_slider.slick('slickNext');}},'json');}});$('#tab04-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#tab04-slider div.item').length;slideAdd(tab04_slider,'actions_games_v3',cnt);});}
if($('#tab05-slider').exists()){tab05_slider=$('#tab05-slider').slick({slidesToShow:11,slidesToScroll:11,prevArrow:$('#tab05-slider-prev-arrow'),nextArrow:$('#tab05-slider-next-arrow'),infinite:false,vertical:true,verticalSwiping:true});var i_tab05=0;$('#tab05-slider-next-arrow').click(function(e){e.preventDefault();i_tab05++;if(i_tab05==1){var cnt=$('#tab05-slider div.item').length;$.get('/ajax/slick_v2.php?a=lower_prices_games&c='+cnt,function(data){if(data.error==0){tab05_slider.slick('slickAdd',data.html);tab05_slider.slick('slickNext');}},'json');}});$('#tab05-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#tab05-slider div.item').length;slideAdd(tab05_slider,'lower_prices_games',cnt);});}
if($('#topNavMenu').exists()){top_nav_menu=$('#topNavMenu').slick({variableWidth:true,slidesToShow:1,slidesToScroll:1,prevArrow:$('#top-nav-prev-arrow'),nextArrow:$('#top-nav-next-arrow'),infinite:true,vertical:false,verticalSwiping:false});}
if($('#ts-slider').exists()){var ts_slider=$('#ts-slider').slick({slidesToShow:1,slidesToScroll:1,prevArrow:$('#ts-prev-arrow'),nextArrow:$('#ts-next-arrow'),infinite:false,vertical:true,verticalSwiping:true});var i_t_s=0;$('#ts-next-arrow').click(function(e){e.preventDefault();i_t_s++;if(i_t_s==1){var cnt=$('.ts-slider-top-list li.item').length,a=$('#ts-slider').attr('data-type');$.get('/ajax/slick_v2.php?a=top_sales&c='+cnt+'&sss'+(a?'&p='+a:''),function(data){if(data.error==0){ts_slider.slick('slickAdd',data.html);ts_slider.slick('slickNext');}},'json');}});$('#ts-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('.ts-slider-top-list li.item').length,amount=$('#ts-slider').attr('data-type');if(slideAdd(ts_slider,'top_sales',cnt,amount)){}});$(document).on('click','.top-sale-filter a',function(){var amount=$(this).attr('data-amount');$.get('/ajax/slick_v2.php?a=top_sales&c=0&p='+amount,function(data){if(data.error==0){var cnt_index=$('#ts-slider div.slide').length;for(var i=0;i<cnt_index;i++){ts_slider.slick('slickRemove',0);}
$('#ts-slider').attr('data-type',amount);if(slideAdd(ts_slider,'top_sales',0,amount)){}}},'json');});$(document).on('click','.top-sale-filters a',function(){var amount=$(this).attr('data-amount');$.get('/ajax/slick_v2.php?a=top_sales&c=0&p='+amount,function(data){if(data.error==0){var cnt_index=$('#ts-slider div.slide').length;for(var i=0;i<cnt_index;i++){ts_slider.slick('slickRemove',0);}
$('#ts-slider').attr('data-type',amount);if(slideAdd(ts_slider,'top_sales',0,amount)){}}},'json');});}
if($('#rg-slider').exists()){rg_slider=$('#rg-slider').slick({slidesToShow:1,slidesToScroll:1,arrows:false,infinite:true,fade:true});$(document).on('click','#rg-refresh',function(){var cnt=$('#rg-slider li.item').length;slideAdd(rg_slider,'rand_games',cnt);$('#rg-slider').slick('slickNext');});}
if($('#rv-slider').exists()){var rv_slider=$('#rv-slider').slick({slidesToShow:1,slidesToScroll:1,arrows:false,infinite:true,fade:true});$(document).on('click','#rv-refresh',function(){var cnt=$('#rv-slider li.item').length;slideAdd(rv_slider,'rand_video',cnt);$('#rv-slider').slick('slickNext');});}
if($('#ls-slider').exists()){$('#ls-slider').slick({slidesToShow:4,slidesToScroll:4,prevArrow:$('#ls-prev-arrow'),nextArrow:$('#ls-next-arrow'),infinite:true,vertical:true,verticalSwiping:true,autoplay:false,autoplaySpeed:false});var i_l_s=1;$('#ls-next-arrow').click(function(e){e.preventDefault();i_l_s++;if(i_l_s==2){$.get('/ajax/slick_v2.php?a=last_sales&c='+i_l_s,function(data){if(data.status=='success'){$('#ls-slider').slick('slickAdd',data.html);$('#ls-slider').slick('slickNext');}},'json');}});$('#ls-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){if(i_l_s>=2&&i_l_s<=6){$.get('/ajax/slick_v2.php?a=last_sales&c='+(i_l_s+1),function(data){if(data.status=='success'){$('#ls-slider').slick('slickAdd',data.html);}},'json');}});}
if($('#ps-slider').exists()){var ps_slider=$('#ps-slider').slick({slidesToShow:1,slidesToScroll:1,prevArrow:$('#ps-prev-arrow'),nextArrow:$('#ps-next-arrow'),infinite:false,fade:true});var i_l_s=0;$('#ps-next-arrow').click(function(e){e.preventDefault();i_l_s++;if(i_l_s==1){var cnt=$('#ps-slider div.item').length;$.get('/ajax/slick_v2.php?a=update_price_games&c='+cnt,function(data){if(data.error==0){$('#ps-slider').slick('slickAdd',data.html);$('#ps-slider').slick('slickNext');}},'json');}});$('#ps-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#ps-slider div.item').length;if(slideAdd(ps_slider,'update_price_games',cnt)){}});}
if($('#as-slider').exists()){var as_slider=$('#as-slider').slick({slidesToShow:1,slidesToScroll:1,prevArrow:$('#as-prev-arrow'),nextArrow:$('#as-next-arrow'),infinite:false,fade:true});var i_l_s=0;$('#as-next-arrow').click(function(e){e.preventDefault();i_l_s++;if(i_l_s==1){var cnt=$('#as-slider div.item').length;$.get('/ajax/slick_v2.php?a=actions_2_games_rand&c='+cnt,function(data){if(data.error==0){$('#as-slider').slick('slickAdd',data.html);$('#as-slider').slick('slickNext');}},'json');}});$('#as-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#as-slider div.item').length;if(slideAdd(as_slider,'actions_2_games_rand',cnt)){}});}
if($('#ns-slider').exists()){$('#ns-slider').slick({slidesToShow:3,slidesToScroll:3,prevArrow:$('#ns-prev-arrow'),nextArrow:$('#ns-next-arrow'),infinite:false});}
if($('#rs-slider').exists()){var rs_slider=$('#rs-slider').slick({slidesToShow:3,slidesToScroll:3,prevArrow:$('#rs-prev-arrow'),nextArrow:$('#rs-next-arrow'),infinite:false,vertical:true,verticalSwiping:true});$(document).on('click','#rs-next-arrow',function(){});}
$('#rs-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#rs-slider div.item').length;slideAdd(rs_slider,'preorders_2_games',cnt);});if($('#ng-slider').exists()){var ng_slider=$('#ng-slider').slick({slidesToShow:6,slidesToScroll:6,prevArrow:$('#ng-prev-arrow'),nextArrow:$('#ng-next-arrow'),infinite:false});$(document).on('click','#ng-next-arrow',function(){var cnt=$('#ng-slider div.item').length;slideAdd(ng_slider,'new_2_games',cnt);});}
if($('#rw-slider').exists()){var rw_slider=$('#rw-slider').slick({slidesToShow:1,slidesToScroll:1,prevArrow:$('#rw-prev-arrow'),nextArrow:$('#rw-next-arrow'),infinite:false,fade:true});var i_t_s=0;$('#rw-next-arrow').click(function(e){e.preventDefault();i_t_s++;if(i_t_s==1){var cnt=$('#rw-slider li.item').length;$.get('/ajax/slick_v2.php?a=digiseller_reviews&c='+cnt,function(data){if(data.error==0){rw_slider.slick('slickAdd',data.html);rw_slider.slick('slickNext');}},'json');}});$('#rw-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#rw-slider li.item').length;if(slideAdd(rw_slider,'digiseller_reviews',cnt)){}});}
if($('#ss-slider').exists()){var ss_slider=$('#ss-slider').slick({slidesToShow:1,slidesToScroll:1,prevArrow:$('#ss-prev-arrow'),nextArrow:$('#ss-next-arrow'),infinite:false,fade:true});$(document).on('click','#ss-next-arrow',function(){});}
$('#ss-slider').on('beforeChange',function(event,slick,currentSlide,nextSlide){var cnt=$('#ss-slider li.item').length;slideAdd(ss_slider,'games_statistics',cnt);});function dump(obj){var out="";if(obj&&typeof(obj)=="object"){for(var i in obj){out+=i+": "+obj[i]+"\n";}}else{out=obj;}
alert(out);}
if($('.catalog-tab-list').exists()){$('#tab01-link').click(function(e){e.preventDefault();$('.catalog-tab-list li').removeClass('active');$(this).parent().addClass('active');$('.catalog-tab-content').removeClass('active');$('#tab01').addClass('active');});$('#tab02-link').click(function(e){e.preventDefault();$('.catalog-tab-list li').removeClass('active');$(this).parent().addClass('active');$('.catalog-tab-content').removeClass('active');$('#tab02').addClass('active');});$('#tab03-link').click(function(e){e.preventDefault();$('.catalog-tab-list li').removeClass('active');$(this).parent().addClass('active');$('.catalog-tab-content').removeClass('active');$('#tab03').addClass('active');});$('#tab04-link').click(function(e){e.preventDefault();$('.catalog-tab-list li').removeClass('active');$(this).parent().addClass('active');$('.catalog-tab-content').removeClass('active');$('#tab04').addClass('active');});$('#tab05-link').click(function(e){e.preventDefault();$('.catalog-tab-list li').removeClass('active');$(this).parent().addClass('active');$('.catalog-tab-content').removeClass('active');$('#tab05').addClass('active');});}
if($('.checkbox-input').exists()){$('.checkbox-input').checkbox({empty:'/template/v2/img/empty.png',cls:'jquery-checkbox'});}
if($('.filter-select').exists()){$('.filter-select').each(function(){if($(this).attr("id")!="toDateSelect"&&$(this).attr("id")!="fromDateSelect"&&$(this).attr("id")!="izdatelSelect"&&$(this).attr("id")!="markSelect"){var sb=new SelectBox({selectbox:$(this),height:206,scrollOptions:{verticalDragMinHeight:16,verticalDragMaxHeight:16}});}});}
if($('.filter-form').exists()){$('.filter-form .field-title > a').click(function(){$(this).parent('.field-title').parent('.filter-field').toggleClass('close');$(this).parent().next('.field-container').slideToggle(300);return false;});if($('.filter-form .show-more-link').exists()){$('.filter-field .show-more-link').click(function(){var hiddenItems=$(this).prev('.filter-checkbox-list').children('li.hidden');if(hiddenItems.is(':hidden')){hiddenItems.fadeIn(300);$(this).html('Свернуть');}else{hiddenItems.fadeOut(300);$(this).html('Показать больше');}});}
$('.filter-checkbox-list .jquery-checkbox').click(function(){$(this).parent('.item').addClass('checked');if($(this).hasClass('jquery-checkbox-checked')){$(this).parent('.item').removeClass('checked');}});$('.filter-checkbox-list .checkbox-label').click(function(){$(this).parent('.item').toggleClass('checked');});$('.filter-checkbox-list .item .checkbox-label').hover(function(){$(this).parent('.item').addClass('hover');},function(){$(this).parent('.item').removeClass('hover');});}
if($('.subscribe .popup-trigger').exists()){$('.subscribe .popup-trigger').click(function(){$('.subscribe-popup').fadeIn();});}
$(document).mouseup(function(e){var container=$(".subscribe-popup");if(!container.is(e.target)&&container.has(e.target).length===0)
{container.fadeOut();}});var isInputSupported='placeholder'in document.createElement('input');var isTextareaSupported='placeholder'in document.createElement('textarea');if(!isInputSupported||!isTextareaSupported){$('[placeholder]').focus(function(){var input=$(this);if(input.val()==input.attr('placeholder')&&input.data('placeholder')){input.val('');input.removeClass('placeholder');}}).blur(function(){var input=$(this);if(input.val()==''){input.addClass('placeholder');input.val(input.attr('placeholder'));input.data('placeholder',true);}else{input.data('placeholder',false);}}).blur().parents('form').submit(function(){$(this).find('[placeholder]').each(function(){var input=$(this);if(input.val()==input.attr('placeholder')&&input.data('placeholder')){input.val('');}})});}});$(function(){$(document).on('click','.random-video-list .item-preview',function(){var yt=$(this).attr('data-youtube');$('<div/>',{id:'opacity-bg'}).appendTo('body').css({'display':'block'});$('<div/>',{id:'pop-block'}).appendTo('body').fadeIn();$('#pop-block').html('<iframe width="640" height="400" src="//www.youtube.com/embed/'+yt+'?autoplay=0" frameborder="0" allowfullscreen></iframe>');return false;});$(document).on('click','#opacity-bg',function(){$('#opacity-bg, #pop-block').remove();return false;});$(document).on('click','.submit-btn',function(){var email=$('#subscribe-email').val();if(email.length&&$('#terms-checkbox').prop('checked')){$.post('/ajax/strr_v2.php',{a:'sub_email',email:email},function(data){if(data.error==0){$('.subscribe-popup').fadeOut();}
else{}},'json');}
return false;});});